### ISSUE TITLE
Multitouch of shapes either works, or is disabled

### ISSUE THREAD

**Issue by naomiyaki** [castiron/tandygram-backend#8]
Currently we can't have more than one active shape at once, but either Hammer.js or the iPad browser allows you to touch two shapes with buggy results! @blnkt do you know if it's simple to disable this, or should we try and add multi shape dragging in the 11th hour? Maybe we could just disable click handling when you're dragging? Let me know!

**Comment by blnkt** [comment]
Went with disabled for now
